name: SAST

on:
  pull_request:
    branches:
      - main

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Bandit - Security Issues in Python code
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          exit_zero: true

  semgrep-full:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:

      # step 1
      - name: clone application source code
        uses: actions/checkout@v3

      # step 2
      - name: full scan
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"

      # step 3
      
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif
          
      # step 4
      - name: Download report
        uses: actions/download-artifact@v2
        with: 
          name: report.sarif
      
      # step 5
      - name: Get current file
        id: scan_summary
        run: cat report.sarif

  depcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Depcheck tool
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'insecure-acebook'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@main
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports
